baseurl = "http://docs.conself.com"
languageCode = "en-us"
title = "CONSELF Docs"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"
publishDir = "docs"
googleAnalytics = "UA-51513359-1"

[params]
  editURL = "https://github.com/CONSELF/conself-docs/tree/master/content/"
  description = "CONSELF Docs"
  author = "Alberto Palazzin"
  autoNav = true
